config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: 'foods#index'
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[new edit create destroy update]
    resources :public_recipes, module: :recipes, only: [:show]
  end

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  # get 'new_food', to: 'recipe_foods#new', as: 'new_recipe_food'
  get 'add_food', to: 'recipe_foods#new', as: 'add_food_recipe'

end

app/controllers/public_recipes_controller.rb
class Recipes::PublicRecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/views/public_recipes/index.html.erb
<h1 class="public-recipe-list-title">Public Recipe List:</h1>

<% if @public_recipes.any? %>
  <ul class="public-recipe-list">
    <% @public_recipes.each do |recipe| %>
      <li class="public-recipe-item">
        <%= link_to "#{recipe.name} by #{recipe.user.name}", public_recipe_path(recipe), class: "public-recipe-link" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="no-public-recipes">No public recipes available.</p>
<% end %>

app/views/public_recipes/show.html.erb
<h1 class="recipe-name"><%= @recipe.name %></h1>

<table class="recipe-detail-table">
  <!-- Table content here -->
</table>

<div class="form-check form-switch">
  <%= form_for(@recipe, url: recipe_path(@recipe), method: :patch, remote: true) do |f| %>
    <%= f.label :public, class: "form-check-label" do %>
      <%= f.check_box :public, class: "form-check-input", checked: @recipe.public? %>
      <%= @recipe.public? ? "Public" : "Private" %>
    <% end %>
    <%= f.submit "Update Visibility", class: "btn btn-primary" %>
  <% end %>
  <span id="visibility-message"></span> <!-- This is where the status change message will be displayed -->
</div>

<div>
  <% if @recipe.user == current_user %>
    <%= button_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-danger" %>
    <%= button_to "Add New Food", new_food_path, class: "btn btn-success add-new-food mt-1", method: :get %>
    <%= link_to "Shopping list", generalshoppinglist_path, class: "btn btn-secondary mt-1" %>
  <% end %>
</div>

<%= link_to 'Back to Recipes List', recipes_path, class: "btn btn-link" %>