config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: 'foods#index'
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[new edit create destroy update]
    resources :public_recipes, module: :recipes, only: [:show]
  end

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  # get 'new_food', to: 'recipe_foods#new', as: 'new_recipe_food'
  get 'add_food', to: 'recipe_foods#new', as: 'add_food_recipe'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true

  def missing_foods(general_foods)
    missing_foods = []

    recipe_foods.each do |recipe_food|
      food = recipe_food.food
      general_food = general_foods.find_by(name: food.name)

      next unless general_food.nil? || general_food.quantity < recipe_food.quantity

      missing_foods << {
        name: food.name,
        quantity: recipe_food.quantity - (general_food&.quantity || 0),
        price: food.price,
        measurement: food.measurement_unit
      }
    end

    missing_foods
  end

  def total_price(foods)
    foods.sum { |food| food[:price] * food[:quantity] }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    @recipes = if user_signed_in?
                 current_user.recipes.or(Recipe.where(public: true))
               else
                 Recipe.where(public: true)
               end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(user_id: current_user.id, **recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe created successfully'
      redirect_to recipes_path
    else
      flash[:alert] = 'Recipe creation failed'
      puts @recipe.errors.full_messages # Check for validation errors in the server logs
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @foods = @recipe_foods.map(&:food)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = 'Recipe visibility updated.'
    else
      flash[:error] = 'Failed to update recipe visibility.'
    end
    respond_to do |format|
      format.html { redirect_to @recipe }
      format.js # Add this line to respond to AJAX request
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(:user).order(created_at: :desc)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_user_recipes.html.erb
# <div class="user-recipes">
#   <h2 class="text-center">Your Recipes</h2>
#   <ul>
#     <% @recipes.each do |recipe| %>
#       <li class="recipe-box"><%= link_to recipe.name, recipe_path(recipe) %></li>
#     <% end %>
#   </ul>
# </div>

app/views/recipes/index.html.erb
<div class="main-container">
    <div class="recipes-container">
        <h1 class="page-title">Recipes</h1>
        <button class="new-button"> <%= link_to "New Recipe", new_recipe_path, class:"new-recipe" %> </button>
    </div>
    <ul class="recipes">
        <% if @recipes.nil?%>
        <li class="no-recipes">There are no recipes yet.</li>
        <% else%>
        <% @recipes.each do |recipe| %>
        <%= render partial: 'shared/recipe', locals: {recipe: recipe} %>
        <% end %>
        <% end %>
    </ul>
</div>

app/views/recipes/new.html.erb
<%= form_with model: @recipe, url: recipes_path, class: 'form' do |form| %>
  <h1 class="new-recipe-title"> New Recipe </h1>
  <div class="field">
      <%= form.label :name, class:"name-label" %>
      <%= form.text_field :name, placeholder:"name", class:"name-input", required: true %>
  </div>
  <div class="field">
      <%= form.label :prepation_time, class:"name-label"%>
      <%= form.number_field :prepation_time,placeholder: "preparation time", class:"name-input", required: true, step: '0.01'%>
  </div>
  <div class="field">
      <%= form.label :cooking_time, class:"name-label"%>
      <%= form.number_field :cooking_time,placeholder:"cooking time", class:"name-input", required: true, step: '0.01' %>
  </div>
  <div class="field">
      <%= form.label :public%>
      <%= form.check_box :public, placeholder:"public", class:"name-input" %>
  </div>
  <div class="field">
      <%= form.label :description, class:"name-label" %>
      <%= form.text_area :description, placeholder: "description",class:"name-input", required: true %>
  </div>
  <div class="field">
      <%= form.submit "Create Recipe", class:"new-button" %>
  </div>
  <%end%>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipe List:</h1>

<% if @public_recipes.any? %>
  <ul class="public-recipe-list">
    <%= render partial: 'shared/public', collection: @public_recipes %>
  </ul>
<% else %>
  <p class="no-public-recipes">No public recipes available.</p>
<% end %>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>
<div class='show-recipe'>
  <div class='show-recipe-left'>
    <p>Preparation time: <%= @recipe.preparation_time %> hours</p>
    <% if can? :destroy, @recipe %>
      <div>
        Public
        <% if @recipe.public %>
          <input type='checkbox' checked>
        <% elsif !@recipe.public %>
          <input type='checkbox'>
        <% end %>
      </div>
    <% else %>
      <% if @recipe.public %>
        <div>
          Public
          <input type='checkbox' checked disabled>
        </div>
      <% elsif !@recipe.public %>
        <div>
          Public
          <input type='checkbox' disabled>
        </div>
      <% end %>
    <% end %>
  </div>

  <p>Cooking time: <%= @recipe.cooking_time %> hours</p>
  <p>Steps go here...</p>
  <div class='show-recipe-left'>
    <button class="new-button">
      <%= link_to "General shopping list", generalshoppinglist_path, class:"new-recipe" %>
    </button>
    <% if can? :update, @recipe %>
      <button class="new-button">
        <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class:"new-recipe" %>
      </button>
    <% end %>
  </div>
  <hr>
  <%= render partial: 'shared/table', locals: {foods: @foods, view: 'recipes'} %>
</div>

<% if @recipe %>
  <table class="recipe-detail-table">
    <thead>
      <tr>
        <th>Preparation Time</th>
        <th>Cooking Time</th>
        <th>Description</th>
        <th>Public</th>
        <th>Status Change</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @recipe.preparation_time %> minutes</td>
        <td><%= @recipe.cooking_time %> minutes</td>
        <td><%= @recipe.description %></td>
        <td><%= @recipe.public ? 'Yes' : 'No' %></td>
        <td>
          <div class="form-check form-switch">
            <%= form_for(@recipe, url: recipe_path(@recipe), method: :patch, remote: true) do |f| %>
              <%= f.label :public, class: "form-check-label" do %>
                <%= f.check_box :public, class: "form-check-input", checked: @recipe.public? %>
                <%= @recipe.public? ? "Public" : "Private" %>
              <% end %>
              <%= f.submit "Update Visibility", class: "btn btn-primary" %>
            <% end %>
          </div>
        </td>
        <td>
          <% if @recipe.user == current_user %>

            <%= button_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-danger btn-sm" %>
            <%= button_to "Add New Food", new_food_path, class: "btn btn-success add-new-food mt-1 btn-sm", method: :get %>
            <%= link_to "Shopping list", generalshoppinglist_path, class: "btn btn-secondary mt-1 btn-sm" %>

          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% else %>
  <p class="private-recipe-message">This recipe is private and cannot be viewed.</p>
<% end %>

<%= link_to 'Back to Recipes List', recipes_path, class: "btn btn-link" %>