config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: 'foods#index'
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[new edit create destroy update]
    resources :public_recipes, module: :recipes, only: [:show]
  end

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  # get 'new_food', to: 'recipe_foods#new', as: 'new_recipe_food'
  get 'add_food', to: 'recipe_foods#new', as: 'add_food_recipe'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :manage, RecipeFood, recipe: { user_id: user.id }

    can :read, Recipe, public: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :price, :quantity, numericality: true
  validates :name, uniqueness: true
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, foreign_key: :food_id, dependent: :delete_all
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true

  def missing_foods(general_foods)
    missing_foods = []

    recipe_foods.each do |recipe_food|
      food = recipe_food.food
      general_food = general_foods.find_by(name: food.name)

      next unless general_food.nil? || general_food.quantity < recipe_food.quantity

      missing_foods << {
        name: food.name,
        quantity: recipe_food.quantity - (general_food&.quantity || 0),
        price: food.price,
        measurement: food.measurement_unit
      }
    end

    missing_foods
  end

  def total_price(foods)
    foods.sum { |food| food[:price] * food[:quantity] }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: :recipe_id
  belongs_to :food, foreign_key: :food_id

  validates :quantity, presence: true

  def calculate_value_by_quantity
    quantity * food.price
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, foreign_key: :user_id
  has_many :recipes, foreign_key: :user_id

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Include the CanCanCan controller add-ons
  include CanCan::ControllerAdditions

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation remember_me])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(user_id: current_user.id, **food_params)
    if @food.save
      flash[:notice] = 'Food created successfully'
      redirect_to foods_path
    else
      flash[:alert] = 'Food creation failed'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    redirect_to request.referrer
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/generalshoppinglist_controller.rb
class GeneralshoppinglistController < ApplicationController
  def index
    @all_recipes = Recipe.all
    @recipes = current_user.recipes.includes(:foods)
    @general_foods = current_user.foods

    @missing_foods = @all_recipes.flat_map { |recipe| recipe.missing_foods(@general_foods) }
    @total_count = @missing_foods.length
    @total_price = Recipe.new.total_price(@missing_foods)
  end
end

app/controllers/public_recipes_controller.rb
class Recipes::PublicRecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_id: params[:recipe_id], **recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'Recipe food created successfully'
      redirect_to recipe_path(params[:recipe_id])
    else
      flash[:alert] = 'Recipe food creation failed'
      render :new
    end
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.user_id = current_user.id
    @recipe_food = RecipeFood.find(params[:id])
    @food = Food.find(@recipe_food.food_id)
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(**update_recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe_id)
    else
      flash[:alert] = 'Failed to update recipe food'
      render :edit
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def update_recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    @recipes = if user_signed_in?
                 current_user.recipes.or(Recipe.where(public: true))
               else
                 Recipe.where(public: true)
               end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(user_id: current_user.id, **recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe created successfully'
      redirect_to recipes_path
    else
      flash[:alert] = 'Recipe creation failed'
      puts @recipe.errors.full_messages # Check for validation errors in the server logs
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @foods = @recipe_foods.map(&:food)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = 'Recipe visibility updated.'
    else
      flash[:error] = 'Failed to update recipe visibility.'
    end
    respond_to do |format|
      format.html { redirect_to @recipe }
      format.js # Add this line to respond to AJAX request
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(:user).order(created_at: :desc)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipes = @user.recipes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/generalshoppinglist_helper.rb
module GeneralshoppinglistHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>

<body>
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span>
  
  <% if user_signed_in? %>
    <%= render partial: 'shared/navbar'%>
  <% end %>
  
  <%= yield %>
</body>
</html>

app/views/shared/_food.html.erb
<tr class="body-elements <%= index % 2 == 0 ? 'even-row' : 'odd-row' %>">
<td class="row-element"> <%=food.name%> </td>
<% if view== 'foods'%>
    <td class="row-element"> <%=food.measurement_unit%> </td>
    <td class="row-element"> $<%=food.price%> </td>
    <td class="row-element"> <%=food.quantity%> </td>
<% else %>
    <% recipe_food = food.recipe_foods.find_by(recipe_id: @recipe.id) %>
    <td class="row-element"> <%=recipe_food.quantity%><%= recipe_food.food.measurement_unit%> </td>
    <td class="row-element"> $<%=recipe_food.calculate_value_by_quantity%> </td>
<% end %>
<td class="row-element">
<% if can? :destroy, food %>
<div class="button-cnt">
    <% if view== 'recipes'%>
        <% if can? :destroy, recipe_food %>
        <button class="new-button"><%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id:@recipe.id, id: recipe_food.id), class:"new-button" %></button>
        <%= button_to "Delete", recipe_recipe_food_path(recipe_id:@recipe.id, id: recipe_food.id), method: :delete, data: {confirm: "Are you sure?"}, class:"new-button" %>
        <% else %>
        <button class="new-button", disabled><%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id:@recipe.id, id: recipe_food.id), class:"new-button" %></button>
        <button class="new-button", disabled><%= button_to "Delete", recipe_recipe_food_path(recipe_id:@recipe.id, id: recipe_food.id), method: :delete, data: {confirm: "Are you sure?"}, class:"new-button"%></button>
        <% end %>
    <% else %>
        <%= button_to "Delete", food, method: :delete, data: {confirm: "Are you sure?"}, class:"new-button" %>
    <% end %>
</div>
<% end %>
</td>
</tr>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>

    <!-- Second Navigation Bar (Centered Navigation) -->
    <nav class="navbar navbar-expand-lg justify-content-center">
      <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= render partial: 'shared/sign_out_link', class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    
    <!-- First Navigation Bar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to 'Foods', foods_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Shopping List', generalshoppinglist_path, class: 'nav-link' %>            </li>
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>

app/views/shared/_public.html.erb
<% @public_recipes.each do |recipe| %>
  <div class='public_recipe'>
    <div class='public_left'>
      <h2 class="recipe-name"><%= link_to recipe.name, recipe_path(recipe.id), class: "recipe-name" %></h2>
      <p>By <%= recipe.user.name %></p>
    </div>
    <div>
      <p>Total food Items: <%= recipe.recipe_foods.length %></p>
      <p>Total price: <b>$</b><%= recipe.recipe_foods.sum { |food| food.quantity * food.food.price } %></p>
    </div>
  </div>
<% end %>

app/views/shared/_recipe.html.erb
<li class="recipe">
<div class="recipe-title-btn">
<h1 class="recipe-name"> <%= link_to recipe.name, recipe, class:"recipe-name"%> </h1>
<% if can? :destroy, recipe %>
<%= button_to "Remove", recipe, method: :delete, data: {confirm: "Are you sure?"}, class:"new-button" %>

<% end %>
</div>
<p class="recipe-des"> <%= recipe.description %></p>
</li>

app/views/shared/_sign_out_link.html.erb
<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
<% end %>

app/views/shared/_table.html.erb
<table class="table-foods">
        <% if foods.nil?%>
        <li class="no-recipes">There are no food yet.</li>
        <% else%>
        <thead class="header-foods">
            <tr class="first-row">
                <th class="fr-food">Food</th>
                <% if view=='foods'%>
                    <th class="fr-food">Measurement Unit</th>
                    <th class="fr-food"> Unit price</th>
                    <th class="fr-food"> Quantity</th>
                <% else %>
                    <th class="fr-food">Quantity</th>
                    <th class="fr-food">Value</th>
                <% end %>
                <th class="fr-food">Actions</th>
            </tr>
        </thead>
        <tbody class="body-foods">
        <% foods.each_with_index do |food, index| %>
        <%= render partial: 'shared/food', locals: {food: food, index: index+1, view:view} %>
        <% end %>
        <% end %>
        </tbody>
    </table>