config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: 'foods#index'
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[new edit create destroy update]
    resources :public_recipes, module: :recipes, only: [:show]
  end

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  # get 'new_food', to: 'recipe_foods#new', as: 'new_recipe_food'
  get 'add_food', to: 'recipe_foods#new', as: 'add_food_recipe'

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: :recipe_id
  belongs_to :food, foreign_key: :food_id

  validates :quantity, presence: true

  def calculate_value_by_quantity
    quantity * food.price
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_id: params[:recipe_id], **recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'Recipe food created successfully'
      redirect_to recipe_path(params[:recipe_id])
    else
      flash[:alert] = 'Recipe food creation failed'
      render :new
    end
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.user_id = current_user.id
    @recipe_food = RecipeFood.find(params[:id])
    @food = Food.find(@recipe_food.food_id)
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(**update_recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe_id)
    else
      flash[:alert] = 'Failed to update recipe food'
      render :edit
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def update_recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), method: :patch) do |form| %>
  <!-- Other form fields -->
  <%= form.hidden_field :authenticity_token, value: form_authenticity_token %>
  <%= form.submit "Update Recipe Food" %>
<% end %>

app/views/recipe_foods/edit.html.erb
<%= form_for @recipe_food, url: recipe_recipe_food_path(@recipe_food), method: :patch, remote: true, class: 'form' do |f| %>
  <h1 class="new-recipe-title"> <%= @food.name %></h1>
  <div class="field">
  <%= f.label :quantity%>
  <%= f.number_field :quantity, class:"name-input" %>
  </div>
  <div class="field">
  <%= f.submit 'Edit', class:"new-button" %>
  </div>

<% end %>

app/views/recipe_foods/new.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_foods_path, class: 'form' do |form| %>
    <h1 class="new-recipe-title"> Add Ingredient </h1>
    <div class="field">
        <%= form.label :quantity, class:"name-label" %>
        <%= form.number_field :quantity, placeholder:"quantity", class:"name-input", required: true, min: 1, step: '0.01' %>
    </div>
    <div class="field">
        <%= form.label :food_id, class:"name-label"%>
        <%= form.select :food_id, options_for_select(@foods.map { |food| [food.name, food.id] }) , class:"name-input" %>
    </div>
    <div class="field">
        <%= form.submit "Add ingredient", class:"new-button" %>
    </div>
    <%end%>